name: 'datavault4dbt_snowflake_demo'
version: '1.0.0'
config-version: 2

profile: 'datavault4dbt_snowflake_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  datavault4dbt_snowflake_demo:
    stage:
      +schema: stage
      +docs:
        node_color: "mediumseagreen"
    raw_vault:
      +schema: core
      +materialized: incremental
      +docs:
        node_color: "orangered"
    business_vault:
      +schema: core
      +docs:
        node_color: "royalblue"
    control:
      +docs:
        node_color: "lightgray"
