version: 2

sources:
  - name: TPC-H_SF1
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: Customer
      - name: LineItem
      - name: Nation
      - name: Orders
      - name: Part
      - name: Partsupp
      - name: Region
      - name: Supplier

models:
  - name: orders_h
    columns:
      - name: hk_h_orders
        tests:
          - unique
  - name: orders_customers_l
    columns:
      - name: hk_l_orders_customers
        tests:
          - unique
  - name: orders_n0_s
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: 
            - hk_h_orders
            - hd_orders_n_s
            - ldts
  - name: orders_n_s
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: 
            - hk_h_orders
            - hd_orders_n_s
            - ledts            
  - name: ma_v0_test
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: 
            - hk_test
            - hd_test
            - ldts        
            - ma_attribute   
  - name: ma_v1_test
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: 
            - hk_test
            - hd_test
            - ledts        
            - ma_attribute            
  - name: lineitems_nl
    columns:
      - name: hk_l_lineitem
        tests:
          - unique
  - name: lineitems_p_ns
    columns:
      - name: hk_l_lineitem
        tests:
          - unique          
  - name: customer_h
    columns:
      - name: hk_h_customer
        tests:
          - unique        
  - name: customer_pb
    columns:
      - name: hk_customer_d
        tests:
          - unique
  - name: customer_rs
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: 
            - hk_h_customer
            - ldts
            - stg                          