version: 2

sources:
  - name: TPC-H_SF1
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: Customer
      - name: LineItem
      - name: Nation
      - name: Orders
      - name: Part
      - name: Partsupp
      - name: Region
      - name: Supplier