
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'datavault4dbt_snowflake_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'datavault4dbt_snowflake_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  datavault4dbt_snowflake_demo:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view

seeds:
  datavault4dbt_snowflake_demo:
    link_entities:
      +column_types:
        link_identifier: varchar(10)
        target_link_table_physical_name: varchar(100)
        source_table_identifier: varchar(50)
        source_column_physical_name: varchar(100)
        prejoin_table_identifier: varchar(100)
        prejoin_table_column_name: varchar(100)
        prejoin_extraction_column_name: varchar(100)
        prejoin_target_column_alias: varchar(100)
        hub_primary_key_physical_name: varchar(100)
        target_column_physical_name: varchar(100)
        target_column_sort_order: int
        target_primary_key_physical_name: varchar(100)
    hub_satellites: 
      +column_types:
        satellite_identifier: varchar(100)
        target_satellite_table_physical_name: varchar(100)
        source_table_identifier: varchar(100)
        source_column_physical_name: varchar(100)
        hub_primary_key_physical_name: varchar(100)
        target_column_physical_name: varchar(100)
        target_column_sort_order: int
    link_satellites: 
      +column_types:
        satellite_identifier: varchar(100)
        target_satellite_table_physical_name: varchar(100)
        source_table_identifier: varchar(100)
        source_column_physical_name: varchar(100)
        link_primary_key_physical_name: varchar(100)
        target_column_physical_name: varchar(100)
        target_column_sort_order: int        


vars:
  #Column Aliases
  datavault4dbt.ldts_alias: 'ldts'
  datavault4dbt.rsrc_alias: 'rsrc'
  datavault4dbt.ledts_alias: 'ledts'
  datavault4dbt.snapshot_trigger_column: 'is_active'
  datavault4dbt.sdts_alias: 'sdts'
  datavault4dbt.stg_alias: 'stg'
  datavault4dbt.is_current_col_alias: 'IS_CURRENT'

  #Hash Configuration
  datavault4dbt.hash: SHA2
  datavault4dbt.hash_datatype: BINARY